spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rules?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: 8ef81fdf-b9f2-4a45-923d-68b186751a05
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**


  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/

server:
  port: 8080
